# Generated by Django 5.1.5 on 2025-04-01 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.CharField(db_column='member_id', help_text='병동 계정 ID (예: wardA101)', max_length=50, primary_key=True, serialize=False, unique=True)),
                ('passwd', models.CharField(db_column='passwd', help_text='로그인 비밀번호', max_length=128)),
                ('name', models.CharField(db_column='name', help_text='담당자 이름', max_length=100)),
                ('email', models.EmailField(blank=True, db_column='email', help_text='이메일 주소', max_length=100, null=True)),
                ('ward_name', models.CharField(db_column='ward_name', default='A병동', help_text='병동 이름 (예: A동중등, 응급병동 등)', max_length=100)),
                ('usage_flag', models.CharField(choices=[('Y', '사용'), ('N', '미사용')], db_column='usage_flag', default='Y', help_text='사용 여부 플래그', max_length=1)),
                ('reg_date', models.DateTimeField(auto_now_add=True, db_column='reg_date', help_text='계정 등록 일자')),
                ('update_date', models.DateTimeField(auto_now=True, db_column='update_date', help_text='계정 수정 일자')),
            ],
            options={
                'db_table': 'member',
            },
        ),
        migrations.CreateModel(
            name='FallRecord',
            fields=[
                ('record_id', models.AutoField(db_column='record_id', help_text='낙상 기록 고유 ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', help_text='환자 이름', max_length=100)),
                ('age', models.PositiveIntegerField(db_column='age', help_text='환자 나이')),
                ('room_number', models.CharField(db_column='room_number', help_text='호실 (예: 101A)', max_length=20)),
                ('fall_date', models.DateTimeField(db_column='fall_date', help_text='낙상 발생 일시')),
                ('fall_level', models.CharField(choices=[('경미', '경미'), ('중간', '중간'), ('심각', '심각')], db_column='fall_level', help_text='낙상 단계', max_length=50)),
                ('fall_area', models.CharField(db_column='fall_area', help_text='낙상 위치', max_length=100)),
                ('note', models.TextField(blank=True, db_column='note', help_text='특이사항 (간호기록, 확인 등)', null=True)),
                ('member', models.ForeignKey(db_column='member_id', help_text='기록한 병동 계정', on_delete=django.db.models.deletion.CASCADE, to='member.member')),
            ],
            options={
                'db_table': 'fall_record',
                'ordering': ['-fall_date'],
            },
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('signup', '회원가입'), ('login', '로그인'), ('logout', '로그아웃')], help_text='로그인/로그아웃/회원가입', max_length=20)),
                ('reg_date', models.DateTimeField(auto_now_add=True, db_column='reg_date', help_text='로그 시간')),
                ('member', models.ForeignKey(db_column='member_id', help_text='로그인 계정 ID', on_delete=django.db.models.deletion.CASCADE, to='member.member')),
            ],
            options={
                'db_table': 'user_log',
            },
        ),
    ]
