# Generated by Django 5.1.5 on 2025-04-03 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='email',
        ),
        migrations.RemoveField(
            model_name='member',
            name='name',
        ),
        migrations.AlterField(
            model_name='fallrecord',
            name='fall_area',
            field=models.CharField(db_column='fall_area', help_text='낙상 부위', max_length=100),
        ),
        migrations.AlterField(
            model_name='fallrecord',
            name='member',
            field=models.ForeignKey(db_column='member_id', help_text='어느 병동에서 발생한 낙상인지 연결', on_delete=django.db.models.deletion.CASCADE, to='member.member'),
        ),
        migrations.AlterField(
            model_name='member',
            name='ward_name',
            field=models.CharField(db_column='ward_name', help_text='병동 이름 (예: A동중등, 응급병동 등)', max_length=100),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='action',
            field=models.CharField(choices=[('signup', '회원가입'), ('login', '로그인'), ('logout', '로그아웃')], db_column='action', help_text='로그 유형', max_length=20),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='member',
            field=models.ForeignKey(db_column='member_id', help_text='로그인한 계정 ID', on_delete=django.db.models.deletion.CASCADE, to='member.member'),
        ),
    ]
