# Generated by Django 5.1.6 on 2025-02-15 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_member_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_id',
            field=models.CharField(db_column='member_id', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='update_date',
            field=models.DateTimeField(auto_now=True, db_column='update_date'),
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('signup', '회원가입'), ('login', '로그인'), ('logout', '로그아웃')], max_length=20)),
                ('log_date', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member')),
            ],
            options={
                'db_table': 'user_log',
            },
        ),
    ]
