# Generated by Django 5.1.5 on 2025-04-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_remove_member_email_remove_member_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='name',
            field=models.CharField(db_column='name', default='관리자', help_text='담당자 이름', max_length=50),
            preserve_default=False,
        ),
    ]
