# Generated by Django 5.1.5 on 2025-04-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_member_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='birth_date',
            field=models.DateField(blank=True, db_column='birth_date', help_text='생년월일', null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='phone',
            field=models.CharField(blank=True, db_column='phone', help_text='전화번호', max_length=20, null=True),
        ),
    ]
