# Generated by Django 5.1.5 on 2025-05-14 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fallalert',
            name='fall_level',
            field=models.CharField(default='심각', max_length=10),
        ),
        migrations.AddField(
            model_name='fallalert',
            name='name',
            field=models.CharField(default='환자A', max_length=50),
        ),
        migrations.AddField(
            model_name='fallalert',
            name='room_number',
            field=models.CharField(default='101호', max_length=20),
        ),
    ]
